language: android
jdk:
  - oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-google-google_play_services
  
addons:
  artifacts: true

before_install:
  - chmod +x gradlew

licenses:
  - android-sdk-license-.+

notifications:
  email: true

script: ./gradlew assembleDebug
