language: android
jdk:
  - oraclejdk7
  - oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23
  - extra-android-m2repository

before_install:
  - chmod +x gradlew

licenses:
  - android-sdk-license-.+

notifications:
  email: true

script: ./gradlew clean test